apiVersion: v1
kind: Service
metadata:
  labels:
      backend.service: backend
  name: backend
spec:
  type: NodePort
  ports:
    - name: "3000"
      port: 3000
      targetPort: 3000
      nodePort: 30100
  selector:
      backend.service: backend
status:
  loadBalancer: {}