apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --volumes hostPath -f docker-compose.yml -o Manifest/
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: backend
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: backend
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --volumes hostPath -f docker-compose.yml -o Manifest/
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/erp-backend-default: "true"
        io.kompose.service: backend
    spec:
      containers:
        - env:
            - name: DB_URL
              value: mongodb://mongod-0.mongodb-service:27017,mongod-1.mongodb-service:27017,mongod-2.mongodb-service:27017
            - name: TOKEN_SECRET
              value: 316O6kPkiezPz7iwEULLMqn6XFmLfp0kos5bbGm0DsIuw7iaOwur9q1ujO2yyq4MRRSZIhuAjf7914x1igAoRePPzZRsaDg2mee5VnhrkaDzB1HinRU5y3JVOrY+sot8gurVdKoWeRR9HnqYV3Z92GdrIY1dJ2UE4sJ/jrJH1O/RYzr54x2NBJPJSlsj9GZ/Ny4c7RK2oWjGIQmYinHm7I5KpNMPdK95vqMEyrKFf/Wntiv82G1GjkS03530r5rBK1Ma0inFmNAf3flEh7kbYvVP/3BrDHadppuNHKjk5PPIfR1nwRWlXhLFWPxh3fZKW9Z59OzK/Jj2VfOcfhBxCg==
          image: harshau04/erp-backend:prod
          name: backend
          ports:
            - containerPort: 3000
              hostPort: 3000
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
